########################################################################
#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
########################################################################

description: "Worker node configuration events from daemon and user logs."

blocks:
  - label: "Worker Config"
    file: [ "daemon.log*", "user.log*" ]
    timeline: 'worker_config'