---
- project:
    check:
      jobs:
        - stx-utilities-tox-linters
        - stx-utilities-tox-pep8
        - stx-utilities-tox-pylint
        - stx-utilities-tox-go-lint
        - stx-utilities-ceph-manager-tox-bandit
        - stx-utilities-ceph-manager-tox-py39
        - stx-utilities-ceph-client-tox-bandit
        - stx-utilities-pci-irq-affinity-agent-tox-py39
        - stx-utilities-pci-irq-affinity-agent-tox-pep8
        - stx-utilities-k8s-coredump-tox-py39
        - stx-utilities-nocloud-factory-install-tox-py39
        - stx-utilities-nocloud-factory-install-tox-pep8
        - stx-utilities-nocloud-factory-install-tox-pylint
        - stx-utilities-nocloud-factory-install-tox-bandit
        - stx-utilities-nocloud-factory-install-tox-linters
    gate:
      jobs:
        - stx-utilities-tox-linters
        - stx-utilities-tox-pep8
        - stx-utilities-tox-pylint
        - stx-utilities-tox-go-lint
        - stx-utilities-ceph-manager-tox-bandit
        - stx-utilities-ceph-manager-tox-py39
        - stx-utilities-ceph-client-tox-bandit
        - stx-utilities-pci-irq-affinity-agent-tox-py39
        - stx-utilities-pci-irq-affinity-agent-tox-pep8
        - stx-utilities-k8s-coredump-tox-py39
        - stx-utilities-nocloud-factory-install-tox-py39
        - stx-utilities-nocloud-factory-install-tox-pep8
        - stx-utilities-nocloud-factory-install-tox-pylint
        - stx-utilities-nocloud-factory-install-tox-bandit
        - stx-utilities-nocloud-factory-install-tox-linters
    post:
      jobs:
        - stx-utilities-upload-git-mirror

- job:
    name: stx-utilities-tox-linters
    parent: tox
    nodeset: debian-bullseye
    vars:
      tox_envlist: linters

- job:
    name: stx-utilities-tox-pep8
    parent: tox
    nodeset: debian-bullseye
    vars:
      tox_envlist: pep8

- job:
    name: stx-utilities-tox-pylint
    parent: tox
    nodeset: debian-bullseye
    description: |
      Run pylint tests
    required-projects:
      - starlingx/fault
      - starlingx/config
    vars:
      bindep_profile: pylint
      tox_envlist: pylint

- job:
    name: stx-utilities-tox-go-lint
    parent: golangci-lint
    description: |
            Run go linting for openbao-monitor
    vars:
      go_version: 1.24.3
      golangci_lint_version: 2.1.6
      zuul_work_dir: "{{ zuul.project.src_dir }}/security/openbao-monitor/source"

- job:
    name: stx-utilities-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/utilities to
      github.com/starlingx/utilities
    vars:
      git_mirror_repository: starlingx/utilities
    secrets:
      - name: git_mirror_credentials
        secret: stx-utilities-github-secret3
        pass-to-parent: true

- job:
    name: stx-utilities-ceph-manager-tox-bandit
    parent: tox
    description: |
      Run bandit test for utilities ceph-mananger
    nodeset: debian-bullseye
    files:
      - ./ceph/ceph-manager/ceph-manager/*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c ./ceph/ceph-manager/ceph-manager/tox.ini

- job:
    name: stx-utilities-ceph-manager-tox-py39
    parent: tox
    description: |
       Run py39 unittests for utilities ceph-mananger
    nodeset: debian-bullseye
    files:
      - ./ceph/ceph-manager/ceph-manager/*
    vars:
      tox_envlist: py39
      python_version: 3.9
      tox_extra_args: -c ./ceph/ceph-manager/ceph-manager/tox.ini

- job:
    name: stx-utilities-ceph-client-tox-bandit
    parent: tox
    description: |
      Run bandit test for utilities python-cephclient
    nodeset: debian-bullseye
    files:
      - ./ceph/python-cephclient/python-cephclient/*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c ./ceph/python-cephclient/python-cephclient/tox.ini

- job:
    name: stx-utilities-pci-irq-affinity-agent-tox-py39
    voting: false
    parent: tox
    description: |
      Run py39 unittests for utilities/pci-irq-affinity-agent
    nodeset: debian-bullseye
    files:
      - ./utilities/pci-irq-affinity-agent/*
    vars:
      tox_envlist: py39
      python_version: 3.9
      tox_extra_args: -c ./utilities/pci-irq-affinity-agent/pci_irq_affinity/tox.ini

- job:
    name: stx-utilities-pci-irq-affinity-agent-tox-pep8
    parent: tox
    description: |
      Run flake8 checks for utilities/pci-irq-affinity-agent
    nodeset: debian-bullseye
    files:
      - ./utilities/pci-irq-affinity-agent/*
    vars:
      tox_envlist: pep8
      tox_extra_args: -c ./utilities/pci-irq-affinity-agent/pci_irq_affinity/tox.ini

- job:
    name: stx-utilities-k8s-coredump-tox-py39
    parent: tox-py39
    description: Run py39 tests for k8s-coredump
    nodeset: debian-bullseye
    files:
      - utilities/k8s-coredump/k8s-coredump/*
    vars:
      tox_envlist: py39
      tox_extra_args: -c utilities/k8s-coredump/k8s-coredump/tox.ini

- job:
    name: stx-utilities-nocloud-factory-install-tox-py39
    parent: tox
    description: Run py39 tests for nocloud-factory-install
    nodeset: debian-bullseye
    files:
      - tools/nocloud-factory-install/*
    vars:
      tox_envlist: py39
      tox_extra_args: -c tools/nocloud-factory-install/tox.ini

- job:
    name: stx-utilities-nocloud-factory-install-tox-pep8
    parent: tox
    description: Run pep8 checks for nocloud-factory-install
    nodeset: debian-bullseye
    files:
      - tools/nocloud-factory-install/*
    vars:
      tox_envlist: pep8
      tox_extra_args: -c tools/nocloud-factory-install/tox.ini

- job:
    name: stx-utilities-nocloud-factory-install-tox-pylint
    parent: tox
    description: Run pylint checks for nocloud-factory-install
    nodeset: debian-bullseye
    files:
      - tools/nocloud-factory-install/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c tools/nocloud-factory-install/tox.ini

- job:
    name: stx-utilities-nocloud-factory-install-tox-bandit
    parent: tox
    description: Run bandit checks for nocloud-factory-install
    nodeset: debian-bullseye
    files:
      - tools/nocloud-factory-install/*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c tools/nocloud-factory-install/tox.ini

- job:
    name: stx-utilities-nocloud-factory-install-tox-linters
    parent: openstack-tox-linters
    description: Run linters (bashate and yamllint) for nocloud-factory-install
    nodeset: debian-bullseye
    files:
      - tools/nocloud-factory-install/*
    vars:
      tox_envlist: linters
      tox_extra_args: -c tools/nocloud-factory-install/tox.ini

- secret:
    name: stx-utilities-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - FLxJIQyczoBax93c5UEdsc5f0/ZRN6LYthjl8Ccj2Mwd5y6OAWLu1MNXPHaans2LFI3Ka
          E2tTOHbriVAOnWbQSG4hscleRQMO4dE3SYzNSQ4cCd56GJy3UyWO4sgHFxPQFEUg90t4B
          4GinzIkIeToPw1yeA0zHxUmMusZr1mGcpZoiarK4MkkLQvacI7i+EtuSVPajqsNDnT4gX
          gqAg4GAOFukBlJMCMSgPeO6EPlYslCEvafN4SX3a8YTWJPwk+y+qQ8qigMty7IoeMHCLX
          hd4/KZGRy+EXGD6DyJu/hCD863C+XxkUSTAEOLq/EBcNy2I5Qgf0viv101rFodV4gUzJH
          GIk/sEvTcKLZLju46e2zX3cn4cXFkP2HlENO60bJEFbK2v6J+bfeuiVVNel6W+5/9ZSEX
          7U7EOpZUB7vCRPpjgqItYlL/zSpbr7PZGLNRMr0tEUIMfGkzZt+RH79dvgE7CZdxlVm1R
          I7kKG7ZLJXyHb+ni74F//RzmE6qngoRaRSOHJxdzsYs0b4/L6D4yeQt6g+bu8IN0AGmrl
          RWzxXXMP3vIC/yEGRRT2iOfw+WV4mVFNyJFUQNHQ6To6dY5mT3GdLZRo8wzgJ8jtz9d28
          um32EES8et9Ww3V81TJKiS5oeTLto2xFUm1oaYZ5SP4TXN8G+Efr1IJTfOYVL4=
        - BqM2vpShxxzN8g04ml8ZhqWGpJug/ctMX8vwZgmkzknB8qB0O6iAzcKOIdvGR/sOzu2p+
          CiJCUR2B1Mq0rnyjLwo7ylsoBabUfM8a6TTjkjf8WwFAl1xQjvDWh6TYYhowDJ3HlBETS
          6KRIq0eG/45n42dqMtxTb7baVOF0ztFkiyVE1CPN5ugxQeYKZ/rKaRfoZj6wqTpcIZ2xn
          WSDpvytZkgPgqsYo1ZG5XHh4htaLPn8O+CafKY0GYB3iAcc3Nu7EW3rkprb0e7ScWS8pX
          Wn8eZBhOGzwSGsrhYvNeHD3m08XkJaL+aCWphgh1KuXeeO9AmccBgPRPi8NRj1E5qwuAy
          sWb0FCn8EIJlCEFjD/gTVpdoPjytrUHOfaQuN4nPRYNFCmm8NDWNyke3A0u3pqgox/yYW
          Oi55cGwSEmkODO3RVPEkSJzInEwUJilHTz9Ysa1yayiUxiakrF+WTsr/ReBZZyljF9+Mj
          1av05PZTRc/lpsEoscCW7sEB6bKzosimNaLOIqA9s10OD3Q3RN2VEki5o7+IeYD/val4d
          FLCfRoX/qICnKpzXV6LZ0ua8RaBwzRrFamVRt4glDpNVougMmJ3TSqCZpxh3xCXRQnvKv
          PhS20ObMyKqQ8OecTE8+7euUOYuiMxHNuqE+MovnxiHCkkBpjlcKqMciTtGbI8=
        - j6IVapHWcmIoWoQOLaRwEIn860Khr3FSma4ATLQu1IzHLVf17u1xK9mefM2agQ7nn0Clr
          RTPp8jGLaL0/060umu33UP3jX0xySFfhBdwz13VxzZuikZPRFHkL6nqg4s0OQW+zVGswt
          FNy/uYI4TKwfNFJQ/HRcYZCp+rRMzX7LwQA8GTY/1LY0DzxxY8u3cKi/HSJLBRA7+st2h
          TAazsBRd+pt3wdhh4gUEdxsmQMfeIdrXowujq+qvcJYbKm++oD1CXoNkYrpPvmqiA3giZ
          vw4tzPK1lBdgcirKl3QW7WkKMklcfKQAv2D6MfGifF/U7oAHejW+98/L56m9ktQPW1xtX
          RXobjmmvCVv5Ccno74o5L0Wl9jFPXiO70fBBKcj1VsECb3E84mQfG/sHKDcFkXHu8k+xh
          8r79XBhq+LgTmdF9SPFspn4tPGhc2R36I84+faeNmYqcA3xjQOvsCErqmBOZ8BPIJg8ld
          VLOUzupDqPG2yjQkTw4GtEdb7Egr0GKZgzYD0RU/NpzS1EPft4SoJZ58KoJOVRXW61Olg
          FcnOI9WDH3XpKTwQ6SysOHf7am5av7bWTajMWRg7KtrIhMhr+8QKPYZaz8K4y4gJNirrV
          O7UqjEx1Ng0XcAtzS08P94FyVLM4vm8zyw75D4mwps3drPEygI3C9oWl88ufR4=
        - nNg9DtaZSu84Xq/BhrsV0gNe5vrPaejK4XAEn1wd2K6tADjtxde7shT/SV7cK5LmNNfwL
          iZayVBdq/Y4q2OoEUz51J4LDjw03UlU7NsEXVeUnHdiSqsYczZLsHl4KqHh9YmhtzrxUg
          PeuDfb2yjVwi0YNUI2fPRLQdynrqMjnCb/0Q9Rf5Ank/4BLGlx5YhyXQlBV2SQsc9k8vC
          Ip8JqyIWRArt2XRJwIygfkhN2gMuNl7nsGN3LnSWdOOVc3q263yayGr7XyH91rkotCQVP
          bvi4OUfJzIxPpLc37qmQjsbkFDAKXxw4s84HhegOs5WMPLd5ltkZuLeaK26vhNigsXux+
          sWU1d2dp6V8aCP7EY1ZKmHElDZSMjufUA5qr/ku6zzEA6JbZMvgU8anNeOmOHMG62iRYi
          QzlNtq2idBoHZjgKe+rWDtOAF7bPZyfkiLmqVFrMK7LZ7rM9iH+PeJmyrePPYDk36B94C
          I4ZlU1UjWgTFLMCc8JuHnITjcZymxKXPTxtCEgtuhVeTn48QD2m2Qq+aLFLnGocii/MGW
          qqtyv5jmDbNhRucSN4DyI08nSv5UkapSZccq2xRa2m2W0ABXuX+AKf3aRVy4fAu/NykTQ
          hlumbrQzP4AXEm10rZhq7Q56vzw0VvLUKAVNNUeykQLIHGos6Q5AUuiwT7vWFI=
        - PPdhnBorm8juP3dl+FVBfex5fz14RYYP+q1dtkJBpOJ196Mw5W9w9QPnbh+t1OslZBWOx
          OmIstEwxllq1NSQwF5lNeAHrw9JFMdQc/IAnLbhCNWZtymJGiQoFa3EKZDojc2p9haDmv
          I6hX1wHKfxd03aMMyK0h/r6D4Mdyqo3o+xeAS6Yt9KX7rqE0bGcbweXZPGVZRzO77FB6G
          2IArdlbpLdpXSy8qEUlkkEbgCNhN9WeFhod82/tUwfXAoCiD5gNdpHjreqbSP3xAYvf7v
          6JSgNEfCWJfg+VzIa0p/s3IWjflRn5yIBCyktcPVt5rK8Vs4fDxeJ1pd+KhM4gc3QLEY+
          bZx4Owuw8lSbn50jnjHh0MJBIdA4YCVWkhy0r6KTL8SULGGqSfZS7T1FUI7N31QmYa+WR
          Bsm53SPPmDQc/0as6AZpXArgaArScarQp4RV4UAadmuLPBnkaNtbGRnvClT/VEwJ4zF7k
          Fb8FHHYXh/9ZiVmvzWoXIHfirFx6KlIKJOIJLfqc+Mh+138RIxfPXSBGuduLVgVnaSE+e
          QOnqApH70Pzbbuna6SzDv16jQ9GPJDmJHVPEF6tCUis8OnRAwSxNU9cSsxOfiCdq1LLxW
          std5bMfAhlQO+h5iclGiPc59dVNPaNfsbQKmR8zqNr+/2mp5JQ/lsc9NYtN77A=
        - VElHhTZ9vcXqiGtWIeG1lwztnYhl/f5QLWKJiOeeXjI8lskYkMfhdF7FL18fY+xb+GR/e
          WsepVWSvbPEbdK5WHkeTMvzx0K+rPNo2qOZy3vcXj8xgZQooixh1QyXx+RVUjfUpCU+nt
          nxyQgr3sQWNPtnZYa8LW89+3jy5EHiA1zahSBiielckhHuDXPiwLUOsx9VDSebNG0OLsh
          FhLcf+NsWMdcpR/P12t9zEFLRXAv1iBsUpn7AHlKFKYyDI9VW5+sGUvHC0/XJV0tACDzv
          1ll6Vnut7A29lcTCvmmC0cu/aAaeiNwoNhnpDuf58JR/nYSkfdsmUb9QqbsHSdg6Ze8PE
          aGqV/T4AYPnK5DeeMIa+6iclPww5op1fSFb5POUjkxa47U3cO+mqbgxUjC0EEWJz0MNfu
          K/vV2JpH4xUznlOA4r6XjaTerxKCi2rtZ9XR91QdfZUfetMAMMkb8gkCVd2gS15RJBqL/
          XxKjPVsncGoCrYqWe3/VjNoGKVZyIW+Gm7/rpa8bk4I/BMMScNe5QddMdxTP/4WHAswzS
          pSUnlRCAYiyR0GiMHjMprgDVSaivz/syJsHGUfzYndWfh1PIzQoYH+X89S/0BW3EpNiNC
          OlqfAXAfx3yHI+hwUT5x1NCf2t+Il+lHVyScASg+atvd5fcdo780Qxp+8o6Ifc=
        - mFdYaoSJ58jTgRDwzp2E24x71sEOAAJyFYePz0pcsLGhNaM64TTUDrF+gJdNnTC3uesdB
          8pQ7Pxtzp2kD7O9mYZM8ffkOG2BdQkDKG/9BEzWiToImMRt602w+gi4gt2Kz/QzP56K9H
          i+/BcvivBrArAzwUcAD3lyeK0G7f+6jkkqMzWqjo1NfRg36UVHkBP7O6zDULleuXDtDlX
          a/pBlI2lqzyiHbkwggdqXj5gevFcyqp4x0dLfeL+HC6YDar+NLzMI8k0eKidykayeD2ZB
          ye8zlJ+7XSe0txqYuL4zmKsu0L27jCcngjoYgoxxUxot9bP5gnXYcdqAcmCDGOurdDav6
          dERgPEbouBW2Ww0Q9x/lXKg0pNUyCG8VEXWZ0LdMzbp37Ip2pAfNV/g6VCWA5gv/+JGjS
          6rVnOdMT6G1umV9dkDtJHvMjZxZx3PQoeiBrlCnLIGvFDog45IoddNYE5gq/i82jkpkgu
          WqCu8YlQJ1y4T2/y6XC+b8gWj9K4wJc6tdM9gUANOPLvGYtsulhGAkxzBdvn9ZtS3Xu7k
          /OfbYd5RfCtzQOhZe3ATlNAcHNpAciP0Y/JsyoZEFTCXJ9dL4VuLa0CFkKKhPiRH6rFJE
          GcEKv6BKljo7+jKxwEhfQ4yMgce5WKCJHwfX3jWq3+cVX/0S3NOX1/2Ca7FaYI=
