# List of packages to be included/installed in ISO

#build-info
#build-info-dev  # not used
build-info

#ceph-manager
ceph-manager

#collector
collector

#hostdata-collectors
engtools

#k8s-coredump
k8s-coredump

#logmgmt
logmgmt

#namespace-utils
namespace-utils

#nfscheck
nfscheck

#platform-util
platform-util-controller
platform-util-noncontroller
platform-util
python3-platform-util

#python-barbicanclient
python3-barbicanclient

#python-cephclient
python3-cephclient

#stx-extensions
stx-extensions

#update-motd
update-motd

#worker-utils
worker-utils
