#!/bin/bash
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# Factory install system health checks triggered during the tests stage
#
# SAMPLE ONLY - REPLACE WITH REAL SYSTEM HEALTH CHECKS
#


echo "System Health Checks - Start"

log_failure () {
    echo "FAIL: $1"
    exit ${2}
}

# check for service impacting alarms
source /etc/platform/openrc
fm --timeout 10 alarm-list --nowrap|grep -e "major\|minor\|warning\|critical"
if [ $? == 0 ]; then
    # Log the health check failure and exit 0 to allow factory-install to finish up.
    # Modify to exit 1 if factory-install should retry check until success.
    log_failure "service impacting alarms present" 0
fi

echo "System Health Checks - Complete"

exit 0
