# Install value Configurations - user configuration overrides
#
# Shared across on-site flows (onsite-enrollment, onsite-restore).
# Install values for subclouds with servers that support Redfish Virtual
# Media Service. Those values will be stored to the central cloud database
# for remote install, ref:
# https://docs.starlingx.io/dist_cloud/kubernetes/installing-a-subcloud-using-redfish-platform-management-service.html
# For on-site flows, if the subcloud is expected to communicate via a vlan,
# both bootstrap_interface and bootstrap_vlan are required. Otherwise, only
# the bootstrap_interface is required.
#
bootstrap_interface: eno1

# If the bootstrap interface is a vlan interface then configure the vlan ID.
# bootstrap_vlan: 5
