#!/usr/bin/env python3
# Copyright (c) 2026 Wind River Systems, Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Combine all network_platform_audit modules into one deployable script.
# Run from the platform-util/ source directory:
#
#   python3 tools/bundle_network_platform_audit.py [-o OUTPUT]
#

import argparse
import os
import re
import stat

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PKG_DIR = os.path.join(SCRIPT_DIR, '..', 'network_platform_audit')

# Modules in strict dependency order (relative to PKG_DIR, no .py suffix)
MODULES = [
    'state',
    'log',
    'run',
    'ssh',
    'sysinv',
    'kube',
    'tests/ts01_availability',
    'tests/ts02_interfaces',
    'tests/ts03_sriov',
    'tests/ts04_addresses',
    'tests/ts05_routes',
    'tests/ts06_ports',
    'tests/ts07_lldp',
    'tests/ts08_addrpools',
    'tests/ts09_dns',
    'tests/ts10_dhcp',
    'tests/ts11_heartbeat',
    'tests/ts12_ipsec',
    'tests/ts13_k8s',
    'tests/ts14_coredns',
    'tests/ts15_cluster_nat',
    'tests/ts16_gnp',
    'tests/ts17_openstack',
    'tests/ts18_mtu',
    'tests/ts19_dc_systemcontroller',
    'tests/ts20_dc_subcloud',
    '__main__',
]

# Matches any import from the package at any indentation level
_INTERNAL_RE = re.compile(
    r'^[ \t]*(?:'
    r'from\s+network_platform_audit(?:\.\w+)*\s+import\s+.*'
    r'|import\s+network_platform_audit(?:\.\w+)*(?:\s+as\s+\w+)?'
    r')\s*$'
)

_ASSIGN_RE = re.compile(r'^([A-Za-z_]\w*)\s*=')


def _read(rel_path):
    with open(os.path.join(PKG_DIR, rel_path + '.py'), encoding='utf-8') as f:
        return f.read()


def _extract_header(content):
    """Return only the copyright/SPDX lines from the leading #-comment block.

    Stops at the first bare '#' separator line so module-specific doc is excluded.
    """
    lines = []
    for line in content.splitlines():
        if line.rstrip() == '#':
            break
        if line.startswith('#'):
            lines.append(line)
        else:
            break
    return '\n'.join(lines)


def _strip_header(content):
    """Remove the leading #-comment block (copyright/module-doc)."""
    lines = content.splitlines(keepends=True)
    i = 0
    while i < len(lines) and (lines[i].startswith('#') or lines[i].rstrip() == ''):
        i += 1
    return ''.join(lines[i:])


def _strip_internal_imports(content):
    """Drop statements that import from network_platform_audit.*, including multi-line ones."""
    result = []
    lines = content.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if _INTERNAL_RE.match(line):
            # Track open parens to skip continuation lines
            depth = line.count('(') - line.count(')')
            i += 1
            while depth > 0 and i < len(lines):
                depth += lines[i].count('(') - lines[i].count(')')
                i += 1
        else:
            result.append(line)
            i += 1
    return '\n'.join(result)


def _transform_state(content):
    """Wrap state.py globals into a SimpleNamespace so all modules can do
    `state.VARIABLE` after their internal imports are stripped.
    Top-level assignments become `state.VAR = value`; other lines are kept.
    """
    preamble = [
        'import types as _npa_types',
        'state = _npa_types.SimpleNamespace()',
        '',
    ]
    body = []
    for line in content.splitlines():
        if _ASSIGN_RE.match(line):
            body.append('state.' + line)
        else:
            body.append(line)
    return '\n'.join(preamble + body)


def bundle(output_path):
    sections = []
    file_header = None
    for mod in MODULES:
        raw = _read(mod)
        if file_header is None:
            file_header = _extract_header(raw)
        content = _strip_header(raw)
        content = _strip_internal_imports(content)
        content = re.sub(r'\n{3,}', '\n\n', content).strip()

        if mod == 'state':
            content = _transform_state(content)

        label = mod.replace('/', '.')
        bar = '-' * 70
        sections.append(f'# {bar}\n# {label}\n# {bar}\n\n{content}')

    header = (
        '#!/usr/bin/env python3\n'
        + file_header + '\n'
        '# Generated by tools/bundle_network_platform_audit.py — do not edit.\n'
    )
    output = header + '\n' + '\n\n\n'.join(sections) + '\n'

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(output)

    mode = os.stat(output_path).st_mode
    os.chmod(output_path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    size = os.path.getsize(output_path)
    print(f'Bundle written: {output_path} ({size:,} bytes, {size // 1024} KB)')


def main():
    parser = argparse.ArgumentParser(
        description='Bundle network_platform_audit into a single deployable script'
    )
    parser.add_argument(
        '-o', '--output',
        default='network_platform_audit',
        help='Output file path (default: ./network_platform_audit)',
    )
    args = parser.parse_args()
    bundle(args.output)


if __name__ == '__main__':
    main()
