#!/bin/bash
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# script to disable the factory install services after the installation is complete
#

echo "Disabling factory install services"

rm -f /var/lib/factory-install/enabled
rm -f /etc/systemd/system-preset/20-factory-install.preset

systemctl daemon-reload
systemctl preset-all

/var/lib/factory-install/utils/send-factory-sel-event finished ok
