#!/bin/bash

set -x

PKG_BUILD_NAME=$1
PKG_BUILD_DIR=$(realpath `pwd`/${PKG_BUILD_NAME})

STX_BASE=$(realpath ${MY_REPO}/stx)
PKG_BASE=$(realpath ${STX_BASE}/utilities/utilities/pci-irq-affinity-agent)

mkdir ${PKG_BUILD_NAME}

mkdir ${PKG_BUILD_DIR}/files
cp -r ${PKG_BASE}/files/* ${PKG_BUILD_DIR}/files/

mkdir ${PKG_BUILD_DIR}/pci_irq_affinity
cp -r ${PKG_BASE}/pci_irq_affinity/* ${PKG_BUILD_DIR}/
