#!/bin/bash

#
# Copyright (c) 2016-2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

. /usr/sbin/customize-banner

banner_path="$1"
if [ -z "${banner_path}" ]; then
    banner_path=$(pwd)
fi

if ! customize_banner "${banner_path}"; then
    exit 1
fi

install_banner_files

# recreate /etc/motd
if grep -q "CentOS" /etc/os-release; then
    /usr/sbin/motd-update
else
    rm -f /etc/motd
fi

exit 0
