#!/bin/bash
set -x

# $1: Name of directory where the source code is extracted to.
#     It corresponds to the build name taken from changelog.OPAE_ZIP

PKG_BUILD_NAME=$1
PKG_BUILD_DIR=$(realpath `pwd`/"${PKG_BUILD_NAME}")

OPAE_SDK_VERSION=1.3.7-5
OPAE_SDK_SOURCE=opae-"${OPAE_SDK_VERSION}".tar.gz

# The OPAE zip file includes opae-sdk, opae.admin and opae.pac_sign source code
OPAE_ZIP=OPAE_1.3.7-5_el7.zip

unzip ./"${OPAE_ZIP}"
if [ $? -ne 0 ]
then
    echo "Failed unzip of source code: ${OPAE_ZIP}"
    exit 1
fi

mv OPAE/source_code/"${OPAE_SDK_SOURCE}" ./
mkdir -p "${PKG_BUILD_DIR}"

# Unpack source code
tar xzf $(basename "${OPAE_SDK_SOURCE}") -C "${PKG_BUILD_DIR}" --strip-components 2

# Patches
sed -i 's|libjson0|libjson-c5|' "${PKG_BUILD_DIR}"/CMakeLists.txt
sed -i 's| -Werror||' "${PKG_BUILD_DIR}"/cmake/modules/compiler_config.cmake
sed -i 's|libjson0-dev|libjson-c-dev|' "${PKG_BUILD_DIR}"/cmake/modules/dependency_notifier.cmake

# Clean-up
rm -rf *.tar.gz
rm -rf "${OPAE_ZIP}" OPAE
