[tox]
envlist = py39,pep8,pylint,bandit,linters
minversion = 4
skipsdist = True

[testenv]
sitepackages = False
basepython = python3.9
allowlist_externals = bash
deps =
    requests
    passlib
    pyyaml
    netaddr
commands = python3 -m unittest discover -s tests -p "test_*.py" -v

[flake8]
max-line-length=80
import-order-style = google
application-import-names = nocloud_utils

[testenv:pep8]
allowlist_externals = bash
deps =
    flake8
    flake8-import-order
    hacking
commands =
    bash -c "find . -path ./.tox -prune \
             -o -type f -print \
             | xargs file \
             | grep 'Python script' \
             | cut -d: -f1 \
             | xargs -r flake8"

[testenv:pylint]
allowlist_externals = bash
deps = pylint
# C0103: invalid-name
# C0114: missing-module-docstring
# C0413: wrong-import-position
# E0401: import-error
# R0801: duplicate-code
# R0902: too-many-instance-attributes
# R0903: too-few-public-methods
# R0904: too-many-public-methods
# R1732: consider-using-with
# R1710: inconsistent-return-statements
# W0718: broad-exception-caught
# W0621: redefined-outer-name
commands =
    bash -c "find . -path ./.tox -prune \
             -o -type f -print \
             | xargs file \
             | grep 'Python script' \
             | cut -d: -f1 \
             | xargs -r pylint --disable=C0103,C0114,C0413,E0401,R0801,R0902,R0903,R0904,R1732,R1710,W0718,W0621 {posargs}"

[testenv:bandit]
allowlist_externals = bash
deps = bandit
# B404: blacklist subprocess
# B603: subprocess_without_shell_equals_true
# B607: start_process_with_partial_path
commands =
    bash -c "find . -path ./.tox -prune \
             -o -type f -print \
             | xargs file \
             | grep 'Python script' \
             | cut -d: -f1 \
             | xargs -r bandit --skip B404,B603,B607"

[testenv:linters]
allowlist_externals = bash
deps =
    bashate
    yamllint
commands =
    bash -c "find . -path ./.tox -prune \
            -o -type f -print \
            | xargs file \
            | grep 'shell script' \
            | cut -d: -f1 \
            | xargs -r bashate -i E006,E042 -v -e 'E*'"
    yamllint -d relaxed config/

