#!/bin/bash
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# script to cleanup the cloud-init services
#

touch /etc/cloud/cloud-init.disabled
rm -f /etc/systemd/system-preset/20-cloud-init.preset

systemctl daemon-reload
systemctl preset-all
